#!/bin/bash

# export PYTHONPATH=/app/lib/python3.12/site-packages:$PYTHONPATH
# export PYTHONPATH=/app/lib64/python3.12/site-packages:$PYTHONPATH

# export NESTML_MODULES_PATH="${NESTML_MODULES_PATH:-/tmp/nestmlmodules}"
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NESTML_MODULES_PATH}

export NEST_SERVER_DISABLE_AUTH=1
export NEST_SERVER_DISABLE_RESTRICTION=1
export NEST_SERVER_ENABLE_EXEC_CALL=1
export NEST_SERVER_MODULES="import nest; import numpy; import numpy as np"

# Start NEST Server as daemon
export NEST_SERVER_DAEMON=1
nest-server start

# if ! command nestml-server 2>&1 >/dev/null
# then
#     # Start NESTML Server as daemon
#     export NESTML_SERVER_DAEMON=1
#     nestml-server start
# fi

# Start NEST Desktop
nest-desktop --no-sandbox --enable-unsafe-swiftshader

# Stop NEST Server
nest-server stop

# if ! command nestml-server 2>&1 >/dev/null
# then
#     # Stop NESTML Server
#     nestml-server stop
# fi